# For customizations see https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
# inspiration https://github.com/pypa/hatch/blob/master/mkdocs.yml
site_name: configlayer
repo_name: liamvdv/configlayer
site_description: configlayer
site_url: https://liamvdv.github.io/configlayer
repo_url: https://github.com/liamvdv/configlayer
edit_uri: blob/master/docs
copyright: "Copyright &copy; Liam van der Viven 2023 - present"
theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
